networks:
  video_generation:
    external: true
    name: Video Generation
services:
  tiktok-api:
    build: .
    networks:
      video_generation:
        ipv4_address: 10.20.0.16
    ports:
      - 8770:8048
    restart: unless-stopped
    volumes:
      - instagram-uploader_instagram-reels_sounds:/app/sounds
      - tiktok-uploader_cookies:/app/CookiesDir
volumes:
  instagram-uploader_instagram-reels_sounds:
    name: instagram-uploader_instagram-reels_sounds
  tiktok-uploader_cookies:
    name: tiktok-uploader_cookies